name: Build, test and upload .pkg to S3

# The scheduler runs at 9 am UTC every day.
on:
  workflow_dispatch:
    inputs:
      ref_name:
        required: true
        type: string
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
  schedule:
    - cron: '0 9 
    outputs:
      tag: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Check tag from workflow input and github ref
        id: check-tag
        run: |
          if [ -n "${{ i
    strategy:
      faows/test-pkg.yaml
    secrets: inherit
    with:
      os: macos
      arch: arm64
      output_arch: aarch64
      version: ${{ matrix.version }}
      tag: ${{ needs.get-tag-name.outputs.tag }}

  macos-x86-64-pkg-test:
    strategy:
      fail-fast: false
      matrix:
        version: [13, 14]
    needs:
      - get-tag-name
      - macos-x86-64-pkg-build
    uses: ./.github/workflows/test-pkg.yaml
    secrets: inherit
    with:
      os: macos
      arch: amd64
      output_arch: x86_64
      version: ${{ matrix.version }}
      tag: ${{ needs.get-tag-name.outputs.tag }}
