# When a third-party action is added (i.e., `uses`), please also add it to `download-licenses` in Makefile.
on:
  push:
    branches:
      -
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_
    steps