name: Release Finch latest version
on:
  workflow_dispatch:
  workflow_call:

jobs:
  get-latest-tag:
    name: Get the latest release tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
            fetch-depth: 0
      - name: 'Get the latest tag'
        id: latest-tag
        uses: "WyriHaximus/github-action-get
    
  build-and-test-finch-pkg:
    needs: get-latest-tag
    uses: ./.github/workflows/build-and-test-pkg.yaml
    secrets: inherit
    with:
      ref_name: ${{ needs.get-latest-tag.outputs.tag }}

  upload-pkg-and-dependency-source-code-to-release:
    needs:
      - get-latest-tag
      - build-and-test-finch-pkg
    uses: ./.github/workflows/upload-installer-to-release.yaml
    secrets: inherit
    with:

      ref_name: ${{ needs.get-latest-tag.outputs.tag }}
